---
# All rights reserved (c) 2020, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

- hosts: localhost
  gather_facts: false
  become: false

  vars:

    rm_version: '1.2.0'

    # >>> CHANGE THIS >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    rm_owner: admin
    rm_group: admin
    rm_roles_pattern: github-user.*
    rm_roles_license_holder: '<github-user@example.com>'
    rm_roles_license_year_to: 2020
    # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CHANGE THIS <<<

    rm_help_text: |
      version {{ rm_version }}
      RoleMaster. Management of roles' meta-data and licenses.

      USAGE

      Create list of roles' paths rm-roles-path
      shell> ansible-playbook rolemaster.yml -t rm-list-roles-path

      Write roles' meta-data to rm_roles_meta_file
      shell> ansible-playbook rolemaster.yml -t rm-list-roles-path,rm-write-roles-meta

      Read roles' meta-data from rm_roles_meta_file
      shell> ansible-playbook rolemaster.yml -t rm-read-roles-meta

      Restore meta-data
      shell> ansible-playbook rolemaster.yml -t rm-restore-roles-meta

      Restore licenses
      shell> ansible-playbook rolemaster.yml -t rm-restore-roles-license

      Copy common files
      shell> ansible-playbook rolemaster.yml -t rm-copy-common-files

      Notes:
      1) Append --check --diff to dry-run and display predicted changes
      2) Append --extra-vars 'rm_debug=true' to display debug messages
      3) Create LICENSE-test and see the diff.
         shell> for i in `find roles -name "MY-PROJECT*"`; do
                (echo $i; cd $i; diff LICENSE LICENSE-test); done

    rm_debug: false
    rm_backup_conf: false
    rm_roles_path: ''  # Get roles_path from ansible.cfg
    # rm_roles_path: '/home/{{ rm_owner }}/.ansible/roles'
    rm_roles_file_mode: '0644'
    rm_roles_meta_file_write: true
    rm_roles_meta_file: '/home/{{ rm_owner }}/.ansible/db/roles_meta.yml'
    rm_roles_meta_dir: '/home/{{ rm_owner }}/.ansible/db/meta'
    rm_roles_license_file: '/home/{{ rm_owner }}/.ansible/db/roles_license.yml'
    rm_roles_license_dir: '/home/{{ rm_owner }}/.ansible/db/license'
    # rm_ansible_lint: '/home/{{ rm_owner }}/bin/ansible-lint -c
    #                   /home/{{ rm_owner }}/.ansible/.ansible-lint'
    rm_known_tags:
      - 'rm-list-roles-path'
      - 'rm-write-roles-meta'
      - 'rm-read-roles-meta'
      - 'rm-restore-roles-meta'
      - 'rm-restore-roles-license'
      - 'rm-copy-common-files'

  tasks:

#    - name: 'rm: Help variables'
#      block:
#        - set_fact:
#            my_tags: "{{ ansible_run_tags|difference(['all']) }}"
#        - debug:
#            var: my_tags
#        - debug:
#            msg: "known tags: {{ my_tags|intersect(rm_known_tags) }}"
#      tags: always

    - name: 'rm: Help'
      block:
        - debug:
            msg: "{{ rm_help_text.split('\n') }}"
        - meta: end_play
      vars:
        my_tags: "{{ ansible_run_tags|difference(['all']) }}"
      when: (my_tags|length == 0) or
            (my_tags|intersect(rm_known_tags)|length == 0)
      tags: always

#    - debug:
#        msg: Continue play
#    - meta: end_play

    - name: 'rm: Set roles_path'
      block:
      - name: 'rm: list-roles-path: Get roles_path from ansible.cfg'
        when: rm_roles_path|length == 0
        set_fact:
          roles_path: "{{ lookup('ini', 'roles_path section=defaults file=ansible.cfg') }}"
      - name: 'rm: list-roles-path: Get roles_path from rm_roles_path'
        when: rm_roles_path|length > 0
        set_fact:
          roles_path: "{{ rm_roles_path }}"
      - name: 'rm: list-roles-path: Debug {{ roles_path }}'
        when: rm_debug|bool
        debug:
          var: roles_path
      - name: 'rm: list-roles-path: Fail when roles_path is undefined'
        when: roles_path is undefined
        fail:
          msg: '[ERROR] roles_path is undefined. End of play.'
      tags: always

    - name: 'rm: Create list of roles paths rm-roles-path'
      import_tasks: tasks/list-roles-path.yml
      tags: rm-list-roles-path

    - name: 'rm: Write roles meta-data to rm_roles_meta_file'
      import_tasks: tasks/write-roles-meta.yml
      tags: rm-write-roles-meta

    - name: 'rm: Read roles meta-data from rm_roles_meta_file'
      import_tasks: tasks/read-roles-meta.yml
      tags: rm-read-roles-meta

    - name: 'rm: Restore roles meta-data from rm_roles_meta_file'
      import_tasks: tasks/restore-roles-meta.yml
      tags: rm-restore-roles-meta

    - name: 'rm: Restore roles license from rm_roles_license_file'
      import_tasks: tasks/restore-roles-license.yml
      tags: rm-restore-roles-license

    - name: 'rm: Copy common files'
      import_tasks: tasks/copy-common-files.yml
      tags: rm-copy-common-files

# EOF
...
