---

- name: "Bump-changelog: Sanity semver"
  ansible.builtin.import_tasks: fn/sanity-semver.yml

- name: "Bump-changelog: Create new_versions_dict"
  ansible.builtin.import_tasks: fn/new-versions-dict.yml

- name: Stat changelog and set chlog_stat_dict
  block:

    - name: "Bump-changelog: Create changelog dir"
      ansible.builtin.file:
        state: directory
        path: "{{ item }}/changelog"
        mode: "0755"
      loop: "{{ my_roles }}"

    - name: "Bump-changelog: Stat changelog file"
      ansible.builtin.stat:
        path: "{{ item }}/changelog/{{ chlog_file }}"
      loop: "{{ my_roles }}"
      loop_control:
        label: "{{ item | basename }}/changelog/{{ chlog_file }}"
      vars:
        major_minor: "{{ new_versions_dict[item] | splitext | first }}"
        chlog_file: "CHANGELOG-v{{ major_minor }}.rst"
      register: out

    - name: "Bump-changelog: Set var chlog_stat_dict"
      ansible.builtin.set_fact:
        chlog_stat_dict: "{{ dict(out.results | json_query('[].[item, stat.exists]')) }}"

    - name: "Bump-changelog: Debug chlog_stat_dict rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        var: chlog_stat_dict | to_nice_yaml
      when: rm_debug | bool

- name: Create changelog. Create release notes and commits blocks.
  block:

    - name: "Bump-changelog: Create changelog files"
      ansible.builtin.copy:
        dest: "{{ item }}/changelog/{{ chlog_file }}"
        mode: "0644"
        content: |
          {{ '=' * chlog_label_len | int }}
          {{ chlog_label }}
          {{ '=' * chlog_label_len | int }}

          .. contents:: Topics

      loop: "{{ chlog_stat_dict | dict2items | rejectattr('value') | map(attribute='key') }}"
      loop_control:
        label: "{{ item | basename }}/changelog/{{ chlog_file }}"
      vars:
        role: "{{ item | basename }}"
        major_minor: "{{ new_versions_dict[item] | splitext | first }}"
        chlog_file: "CHANGELOG-v{{ major_minor }}.rst"
        chlog_label: "{{ role }} {{ major_minor }} Release Notes"
        chlog_label_len: "{{ chlog_label | length }}"

    - name: "Bump-changelog: Get commits {{ semver }}"
      ansible.builtin.script:
        cmd: "{{ rm_scripts_dir }}/log-oneline.sh {{ item }} list"
        chdir: "{{ item }}"
      loop: "{{ my_roles }}"
      register: out
      check_mode: false
      changed_when: false

    - name: "Bump-changelog: Set var commits_dict"
      ansible.builtin.set_fact:
        commits_dict: "{{ dict(my_roles | zip(commits)) }}"
      vars:
        commits: "{{ out.results | json_query('[].stdout_lines') | map('from_yaml') }}"

    - name: "Bump-changelog: Create release blocks in changelog files"
      ansible.builtin.blockinfile:
        path: "{{ item }}/changelog/{{ chlog_file }}"
        marker: '# {mark} Release notes {{ new_tag }}'
        insertafter: '.. contents:: Topics'
        block: |
          {{ new_tag }}
          {{ '=' * new_tag_len | int }}

          Release Summary
          ---------------
          Maintenance update.

          Major Changes
          -------------

          Minor Changes
          -------------
          {{ commits_dict[item] | to_nice_yaml }}

          Bugfixes
          --------

          Breaking Changes / Porting Guide
          --------------------------------

      loop: "{{ my_roles }}"
      loop_control:
        label: "{{ item | basename }}/changelog/{{ chlog_file }}"
      vars:
        new_tag: "{{ new_versions_dict[item] }}"
        new_tag_len: "{{ new_tag | length }}"
        major_minor: "{{ new_tag | splitext | first }}"
        chlog_file: "CHANGELOG-v{{ major_minor }}.rst"

# EOF
