---

- name: "Rm copy-common-files: Copy common files"
  ansible.builtin.copy:
    src: files/
    dest: "{{ item }}"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    mode: "0664"
    backup: "{{ rm_backup_conf }}"
  loop: "{{ my_roles }}"

# EOF
