---

- name: Set my_roles list
  block:

    - name: "List-modified-roles: Find roles in {{ my_roles_path }}"
      ansible.builtin.find:
        paths: "{{ my_roles_path }}"
        patterns: "{{ rm_roles_pattern }}"
        file_type: directory
      register: results

    - name: "List-modified-roles: Collect my_roles"
      ansible.builtin.set_fact:
        my_roles: "{{ my_roles_all | difference(my_roles_rej) | intersect(my_roles_sel) | sort }}"
      vars:
        regex_reject: "({{ my_roles_reject | join('|') }})$"
        regex_select: "({{ my_roles_select | join('|') }})$"
        my_roles_all: "{{ results.files | json_query('[].path') | sort }}"
        my_roles_rej: "{{ my_roles_reject | ternary(my_roles_all | select('search', regex_reject), []) }}"
        my_roles_sel: "{{ my_roles_select | ternary(my_roles_all | select('search', regex_select), my_roles_all) }}"

- name: Set modified my_roles list
  block:

    - name: "List-modified-roles: Get modified roles"
      ansible.builtin.script:
        cmd: "{{ rm_scripts_dir }}/{{ script }} {{ item | quote }}"
        chdir: "{{ item }}"
      loop: "{{ my_roles }}"
      vars:
        script: "status-short.sh"
      register: out
      check_mode: false
      changed_when: false

    - name: "List-modified-roles: Debug result rm_debug2={{ rm_debug2 }}"
      ansible.builtin.debug:
        var: out
      when: rm_debug2 | bool

    - name: "List-modified-roles: Set modified roles my_roles"
      ansible.builtin.set_fact:
        my_roles: "{{ out.results |
	              rejectattr('stderr', 'search', 'Everything up-to-date') |
                      json_query('[].stdout_lines') | map('last') | map('trim') | map('from_yaml') | combine |
	              dict2items | selectattr('value') | map(attribute='key') }}"

    - name: "List-modified-roles: Debug modified my_roles rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        msg: |
          Number of roles: {{ my_roles | length }}"
          my_roles:
            {{ my_roles | to_nice_yaml(indent=2) | indent(2) }}
      when: rm_debug | bool

# EOF
