---

- name: 'rm: read-objects: Include vars meta'
  include_vars: "{{ rm_roles_meta_file }}"
- name: 'rm: read-objects: Debug meta'
  when: rm_debug|bool
  debug:
    var: rm_roles_meta

# - debug:
#     var: rm_roles_meta.keys()
#   when: rm_debug|bool
# - debug:
#     msg: "{{ item.key }}"
#   loop: "{{ rm_roles_meta|dict2items }}"
#   loop_control:
#     label: "{{ item.value.galaxy_info.role_name|default(item.key) }}"
#   when: rm_debug|bool

# EOF
...
