---
- name: "Rm: read-objects: Include vars meta"
  ansible.builtin.include_vars: "{{ rm_roles_meta_file }}"

- name: "Rm: read-objects: Debug meta"
  ansible.builtin.debug:
    var: rm_roles_meta
  when: rm_debug | bool

# - ansible.builtin.debug:
#     var: rm_roles_meta.keys()
#   when: rm_debug|bool
# - ansible.builtin.debug:
#     msg: "{{ item.key }}"
#   loop: "{{ rm_roles_meta|dict2items }}"
#   loop_control:
#     label: "{{ item.value.galaxy_info.role_name|default(item.key) }}"
#   when: rm_debug|bool

# EOF
