---

- name: 'rm restore-meta: Include vars'
  ansible.builtin.include_vars: "{{ rm_roles_meta_file }}"

- name: 'rm restore-meta: Debug'
  ansible.builtin.debug:
    var: rm_roles_meta
  when: rm_debug|bool

- name: 'rm restore-meta: Create meta files'
  ansible.builtin.template:
    src: templates/main.yml.j2
    dest: "{{ item.key }}/meta/main.yml"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    backup: "{{ rm_backup_conf }}"
#   validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ rm_roles_meta|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.key|basename not in rm_roles_blacklist

# EOF
...
