---

- name: "Restore-travis: Include vars"
  ansible.builtin.include_vars: "{{ rm_roles_travis_file }}"

- name: Restore travis
  vars:
    regex_select: "({{ my_roles_select | join('|') }})$"
    rm_roles_travis_list: "{{ rm_roles_travis | dict2items }}"
    my_roles_travis: "{{ my_roles_select |
                         ternary(rm_roles_travis_list | selectattr('key', 'search', regex_select),
                                 rm_roles_travis_list) }}"
  block:

    - name: "Restore-travis: Debug rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        msg: |-
          my_roles_select:
            {{ my_roles_select | to_nice_yaml(indent=2) | indent(2) }}
          my_roles_travis:
            {{ my_roles_travis | to_nice_yaml(indent=2) | indent(2) }}
      when: rm_debug | bool

    - name: "Restore-travis: Create travis files"
      ansible.builtin.template:
        src: templates/travis.yml.j2
        dest: "{{ item.key }}/.travis.yml"
        owner: "{{ rm_owner }}"
        group: "{{ rm_group }}"
        mode: "{{ rm_roles_file_mode }}"
        backup: "{{ rm_backup_conf }}"
        # validate: "{{ rm_ansible_lint }} %s"
      loop: "{{ my_roles_travis }}"
      register: out
      loop_control:
        label: "{{ item.key }}"

    - name: "Restore-travis: Set my_roles"
      ansible.builtin.set_fact:
        my_roles: "{{ out.results | json_query('[?changed].item.key') }}"

    - name: "Restore-travis: Debug my_roles rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        var: my_roles | to_nice_yaml
      when: rm_debug | bool

# EOF
