---

- name: 'rm restore-meta: Include vars'
  include_vars: "{{ rm_roles_meta_file }}"

- name: 'rm restore-meta: Debug'
  when: rm_debug|bool
  debug:
    var: rm_roles_meta

- name: 'rm restore-meta: Create meta files'
  when: rm_roles_blacklist|intersect([item.key])|length == 0
  template:
    src: templates/main.yml.j2
    dest: "{{ item.key }}/meta/main.yml"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    backup: "{{ rm_backup_conf }}"
#   validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ rm_roles_meta|dict2items }}"
  loop_control:
    label: "{{ item.value.galaxy_info.role_name|default(item.key) }}"

# EOF
...
