---

- name: 'rm restore-travis: Include vars'
  ansible.builtin.include_vars: "{{ rm_roles_travis_file }}"

- name: 'rm restore-travis: Debug'
  ansible.builtin.debug:
    var: rm_roles_travis
  when: rm_debug|bool

- name: 'rm restore-travis: Create travis files'
  ansible.builtin.template:
    src: templates/travis.yml.j2
    dest: "{{ item.key }}/.travis.yml"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    backup: "{{ rm_backup_conf }}"
#   validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ rm_roles_travis|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.key|basename not in rm_roles_blacklist


# EOF
...
