---

- name: 'rm: retore-license: Include vars'
  ansible.builtin.include_vars: "{{ rm_roles_license_file }}"

- name: 'rm: retore-license: Debug'
  ansible.builtin.debug:
    var: rm_roles_license
  when: rm_debug|bool

- name: 'rm: restore-license: Create roles license files'
  ansible.builtin.template:
    src: "templates/{{ item.value.template }}"
    dest: "{{ roles_path }}/{{ item.key }}/LICENSE"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    mode: "{{ rm_roles_file_mode }}"
    backup: "{{ rm_backup_conf }}"
#   validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ rm_roles_license|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.key|basename not in rm_roles_blacklist

# EOF
...
