---

- name: 'rm restore-travis: Include vars'
  ansible.builtin.include_vars: "{{ rm_roles_travis_file }}"

- name: 'rm restore-travis: Debug'
  ansible.builtin.debug:
    msg: |-
      rm_roles_select_list:
        {{ rm_roles_select_list|to_nice_yaml|indent(2) }}
      {% if rm_roles_select_list|length == 0 %}
      rm_roles_travis:
        {{ rm_roles_travis|to_nice_yaml|indent(2) }}
      {% else %}
      rm_roles_travis: (selected)
      {% for i in rm_roles_select_list %}
        {{ roles_path }}/{{ i }}:
          {{ rm_roles_travis[roles_path ~ '/' ~ i]|to_nice_yaml|indent(4) }}
      {% endfor %}
      {% endif %}
  when: rm_debug|bool

- name: 'rm restore-travis: Create travis files'
  ansible.builtin.template:
    src: templates/travis.yml.j2
    dest: "{{ item.key }}/.travis.yml"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    backup: "{{ rm_backup_conf }}"
#   validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ rm_roles_travis|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.key|basename in rm_roles_select_list or rm_roles_select_list|length == 0
    - item.key|basename not in rm_roles_blacklist


# EOF
...
