---

- name: 'rm restore-meta: Include vars'
  ansible.builtin.include_vars: "{{ rm_roles_meta_file }}"

- name: 'rm restore-meta: Debug'
  ansible.builtin.debug:
    msg: |-
      rm_roles_select_list:
        {{ rm_roles_select_list|to_nice_yaml|indent(2) }}
      {% if rm_roles_select_list|length == 0 %}
      rm_roles_meta:
        {{ rm_roles_meta|to_nice_yaml|indent(2) }}
      {% else %}
      rm_roles_meta: (selected)
      {% for i in rm_roles_select_list %}
        {{ roles_path }}/{{ i }}:
          {{ rm_roles_meta[roles_path ~ '/' ~ i]|to_nice_yaml|indent(4) }}
      {% endfor %}
      {% endif %}
  when: rm_debug|bool

- name: 'rm restore-meta: Create meta files'
  ansible.builtin.template:
    src: templates/main.yml.j2
    dest: "{{ item.key }}/meta/main.yml"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    backup: "{{ rm_backup_conf }}"
#   validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ rm_roles_meta|dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when:
    - item.key|basename in rm_roles_select_list or rm_roles_select_list|length == 0
    - item.key|basename not in rm_roles_blacklist

# EOF
...
