---

- name: 'rm: retore-roles-license: Include vars'
  include_vars: "{{ rm_roles_license_file }}"
- name: 'rm: retore-roles-license: Debug'
  when: rm_debug
  debug:
    var: rm_roles_license
- name: 'rm: restore-roles-license: Create roles license files'
  template:
    src: "templates/{{ item.value.template }}"
    dest: "{{ roles_path }}/{{ item.key }}/LICENSE"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    mode: "{{ rm_roles_file_mode }}"
    backup: "{{ rm_backup_conf }}"
  loop: "{{ rm_roles_license|dict2items }}"

# EOF
...
