---

- name: "Rm restore-travis: Include vars"
  ansible.builtin.include_vars: "{{ rm_roles_travis_file }}"

- name: "Rm restore-travis: Debug"
  ansible.builtin.debug:
    msg: |-
      rm_roles_select_list:
        {{ rm_roles_select_list | to_nice_yaml(indent=2) | indent(2) }}
      {% if rm_roles_select_list | length == 0 %}
      rm_roles_travis:
        {{ rm_roles_travis | to_nice_yaml(indent=2) | indent(2) }}
      {% else %}
      rm_roles_travis: (selected)
        {{ rm_roles_travis | dict2items | selectattr('key', 'search', rm_roles_select_list | join('|')) | items2dict | to_nice_yaml(indent=2) | indent(2) }}
      {% endif %}
  when: rm_debug | bool

- name: "Rm restore-travis: Create travis files"
  ansible.builtin.template:
    src: templates/travis.yml.j2
    dest: "{{ item.key }}/.travis.yml"
    owner: "{{ rm_owner }}"
    group: "{{ rm_group }}"
    mode: "0664"
    backup: "{{ rm_backup_conf }}"
    # validate: "{{ rm_ansible_lint }} %s"
  loop: "{{ _select }}"
  loop_control:
    label: "{{ item.key }}"
  vars:
    _select: |
      {% if rm_roles_select_list | length == 0 %}
      {{ rm_roles_travis | dict2items }}
      {% else %}
      {{ rm_roles_travis | dict2items | selectattr('key', 'search', rm_roles_select_list | join('|')) }}
      {% endif %}
  when: item.key | basename not in rm_roles_blacklist

# EOF
...
