---

- name: Update docs themes
  vars:
    regex_select: "({{ my_roles_select | join('|') }})$"
    rm_docs_roles_list: "{{ rm_docs_roles | dict2items }}"
    my_docs_roles: "{{ my_roles_select |
                       ternary(rm_docs_roles_list | selectattr('key', 'search', regex_select),
                               rm_docs_roles_list) }}"
  block:

    - name: "Rm update_docs_themes: Debug rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        msg: |-
          my_roles_path: {{ my_roles_path }}

          my_roles_select:
            {{ my_roles_select | to_nice_yaml(indent=2) | indent(2) }}
          my_docs_roles:
            {{ my_docs_roles | to_nice_yaml(indent=2) | indent(2) }}
          rm_docs_themes: |
            {{ rm_docs_themes | to_nice_yaml(indent=2) | indent(2) }}
      when: rm_debug | bool

    - name: "Rm update_docs_themes: Update docs themes"
      ansible.posix.synchronize:
        src: "{{ rm_docs_themes[item.1] }}"
        dest: "{{ my_roles_path }}/{{ item.0.key }}/{{ item.0.value.themes_path }}/"
        recursive: true
        archive: false
        checksum: true
      loop: "{{ my_docs_roles | subelements('value.themes') }}"
      register: out
      loop_control:
        label: "{{ item.0.key }} {{ item.1 }}"

    - name: "Rm update_docs_themes: Debug results rm_debug2={{ rm_debug2 }}"
      ansible.builtin.debug:
        var: out
      when: rm_debug2 | bool

    - name: "Rm update_docs_themes: Set my_roles"
      ansible.builtin.set_fact:
        my_roles: "{{ out.results | json_query('[?changed].item[].key') | unique }}"

    - name: "Rm update_docs_themes: Debug my_roles rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        var: my_roles | to_nice_yaml
      when: rm_debug | bool

# EOF
