---

- name: "Rm update_docs_themes: Include vars meta"
  ansible.builtin.include_vars: "{{ rm_roles_docs_file }}"

- name: "Rm update_docs_themes: Debug"
  ansible.builtin.debug:
    msg: |-
      rm_roles_select_list:
        {{ rm_roles_select_list | to_nice_yaml(indent=2) | indent(2) }}
      rm_roles_blacklist:
        {{ rm_roles_blacklist | to_nice_yaml(indent=2) | indent(2) }}
      rm_roles_docs:
        {{ rm_roles_docs | to_nice_yaml(indent=2) | indent(2) }}
  when: rm_debug | bool

- name: "Rm update_docs_themes: Update docs themes"
  ansible.posix.synchronize:
    src: "{{ rm_roles_docs_themes[item.1] }}"
    dest: "{{ roles_path }}/{{ item.0.key }}/{{ item.0.value.themes_path }}/"
    rsync_opts:
      - --ignore-times
    # owner: "{{ rm_owner }}"
    # group: "{{ rm_group }}"
    # mode: "0664"
  loop: "{{ rm_roles_docs | dict2items | subelements('value.themes') }}"
  loop_control:
    label: "{{ item.0.key }} {{ item.1 }}"
  when:
    - item.0.key | basename in rm_roles_select_list or rm_roles_select_list | length == 0
    - item.0.key | basename not in rm_roles_blacklist

# EOF
...
