---

- name: "Rm update_docs_themes: Include vars"
  ansible.builtin.include_vars: "{{ rm_roles_docs_file }}"

- name: Update docs themes
  vars:
    regex_select: "({{ my_roles_select | join('|') }})$"
    rm_roles_docs_list: "{{ rm_roles_docs | dict2items }}"
    my_roles_docs: "{{ my_roles_select |
                       ternary(rm_roles_docs_list | selectattr('key', 'search', regex_select),
                               rm_roles_docs_list) }}"
  block:

    - name: "Rm update_docs_themes: Debug rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        msg: |-
          my_roles_path: {{ my_roles_path }}

          my_roles_select:
            {{ my_roles_select | to_nice_yaml(indent=2) | indent(2) }}
          my_roles_docs:
            {{ my_roles_docs | to_nice_yaml(indent=2) | indent(2) }}
          rm_roles_docs_themes: |
            {{ rm_roles_docs_themes | to_nice_yaml(indent=2) | indent(2) }}
      when: rm_debug | bool

    - name: "Rm update_docs_themes: Update docs themes"
      ansible.posix.synchronize:
        src: "{{ rm_roles_docs_themes[item.1] }}"
        dest: "{{ my_roles_path }}/{{ item.0.key }}/{{ item.0.value.themes_path }}/"
        recursive: true
        archive: false
        checksum: true
      loop: "{{ my_roles_docs | subelements('value.themes') }}"
      register: out
      loop_control:
        label: "{{ item.0.key }} {{ item.1 }}"

    - name: "Restore-license: Debug results rm_debug2={{ rm_debug2 }}"
      ansible.builtin.debug:
        var: out
      when: rm_debug2 | bool

    - name: "Restore-license: Set my_roles"
      ansible.builtin.set_fact:
        my_roles: "{{ out.results | json_query('[?changed].item[].key') | unique }}"

    - name: "Restore-license: Debug my_roles rm_debug={{ rm_debug }}"
      ansible.builtin.debug:
        var: my_roles | to_nice_yaml
      when: rm_debug | bool

# EOF
