---
- include_tasks: fn/roles-meta-objects.yml
  loop: "{{ rm_roles_path|default([]) }}"
- name: 'rm: write-roles-meta: Debug'
  debug:
    var: rm_roles_meta
  when: rm_debug
- name: 'rm: write-roles-meta: Create dirs'
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ rm_roles_license_dir }}"
    - "{{ rm_roles_meta_dir }}"
- block:
    - name: 'rm: write-roles-meta: Create temp file'
      tempfile:
        path: "{{ rm_roles_meta_dir }}"
      register: result
    - name: 'rm: write-roles-meta: Set temp file permissions'
      when: not ansible_check_mode
      file:
        path: "{{ result.path }}"
        mode: "{{ rm_roles_file_mode }}"
    - name: 'rm: write-roles-meta: Debug temp file'
      when:
        - rm_debug
        - not ansible_check_mode
      debug:
        msg: "{{ result.path }}"
    - name: 'rm: write-roles-meta: Debug meta link'
      when: rm_debug
      debug:
        msg: "{{ rm_roles_meta_file }}"
    - name: 'rm: write-roles-meta: Link temp file to {{ rm_roles_meta_file }}'
      when: not ansible_check_mode
      file:
        state: link
        src: "{{ result.path }}"
        dest: "{{ rm_roles_meta_file }}"
    - name: 'rm: write-roles-meta: Write {{ rm_roles_meta_file }}'
      template:
        src: templates/roles_meta.j2
        dest: "{{ rm_roles_meta_file }}"
        follow: true
  when: rm_roles_meta_file_write

# EOF
...
