---

- block:
    - name: "configure: Create directories for Ansible configuration"
      file:
        dest: "{{ item.path | dirname }}"
        state: "directory"
      loop: "{{ ma_config }}"
    - name: "configure: Create Ansible configuration from template"
      template:
        src: "{{ item.template }}"
        dest: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ ma_config }}"
  when:
    - ma_config_type|lower == "template"
    - ma_config > 0

- name: "configure: Configure Ansible"
  lineinfile:
    path: "{{ item.0.path }}"
    owner: "{{ item.0.owner }}"
    group: "{{ item.0.group }}"
    mode: "{{ item.0.mode }}"
    regexp: "^{{ item.1.key }}"
    line: "{{ item.1.key }}={{ item.1.value }}"
    insertafter: "\\[{{ item.1.section }}\\]"
    create: yes
  with_subelements:
    - "{{ ma_config }}"
    - config
  when:
    - ma_config_type|lower == "lineinfile"
    - ma_config > 0

# EOF
...
