---

- name: "Ansible: Debug"
  vars:
    msg: |
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      ansible_distribution_version [ {{ ansible_distribution_version }} ]
      ansible_distribution_release [ {{ ansible_distribution_release }} ]

      ma_install [ {{ ma_install }} ]
      ma_packages [
      {{ ma_packages | to_nice_yaml }} ]
      ma_config_type [ {{ ma_config_type }} ]
      ma_config_template_default [ {{ ma_config_template_default }} ]
      ma_config [
      {{ ma_config | to_yaml }} ]
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
