---

- name: "devel: Checkout repository"
  block:
    - name: "devel: Create directory {{ ma_repo_dir }}"
      ansible.builtin.file:
        state: directory
        path: "{{ ma_repo_dir }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group|default(omit) }}"
        mode: "{{ ma_devel_dmode|default(omit) }}"
      tags: ma_repo_path
    - name: "devel: Checkout {{ ma_repo_version }}"
      become: "{{ ma_devel_owner }}"
      ansible.builtin.git:
        repo: "{{ ma_repo_url }}"
        version: "{{ ma_repo_version }}"
        dest: "{{ ma_repo_dir }}"
  when: ma_repo|bool
  tags: ma_devel_repo

- name: "devel: Get release notes"
  block:
    - name: "devel: Create directories for release notes"
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group|default(omit) }}"
        mode: "{{ ma_devel_dmode|default(omit) }}"
      loop:
        - "{{ ma_rnotes_core_dir }}"
        - "{{ ma_rnotes_build_dir }}"
      tags: ma_rnotes_path
    - name: "devel: Get core release notes {{ ma_rnotes_core_list }}"
      check_mode: false  # Note 1.
      ansible.builtin.get_url:
        url: "{{ _url }}"
        dest: "{{ (ma_rnotes_core_dir, _file)|community.general.path_join }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group }}"
      loop: "{{ ma_rnotes_core_list }}"
      loop_control:
        label: "{{ _url }}"
      vars:
        _file: "CHANGELOG-v{{ item }}.rst"
        _url: "{{ (ma_rnotes_core_url ~ item, 'changelogs', _file)|community.general.path_join }}"
    - name: "devel: Get build release notes {{ ma_rnotes_build_list }}"
      check_mode: false  # Note 1.
      ansible.builtin.get_url:
        url: "{{ _url }}"
        dest: "{{ (ma_rnotes_build_dir, _file)|community.general.path_join }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group }}"
      loop: "{{ ma_rnotes_build_list }}"
      loop_control:
        label: "{{ _url }}"
      vars:
        _file: "CHANGELOG-v{{ item }}.rst"
        _url: "{{ (ma_rnotes_build_url, item, _file)|community.general.path_join }}"
  when: ma_rnotes|bool
  tags: ma_devel_rnotes


# Notes:
#
# 1) The module get_url does not support diff_mode. It will always
#    report *changed* in check_mode.

# EOF
...
