---
- name: "Devel: Checkout repository"
  when: ma_repo | bool
  tags: ma_devel_repo
  block:

    - name: "Devel: Create directory {{ ma_repo_dir }}"
      tags: ma_repo_path
      ansible.builtin.file:
        state: directory
        path: "{{ ma_repo_dir }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group | d(omit) }}"
        mode: "{{ ma_devel_dmode | d(omit) }}"

    - name: "Devel: Checkout {{ ma_repo_version }}"
      become: "{{ ma_devel_owner }}"
      ansible.builtin.git:
        repo: "{{ ma_repo_url }}"
        version: "{{ ma_repo_version }}"
        dest: "{{ ma_repo_dir }}"

- name: "Devel: Get release notes"
  when: ma_rnotes | bool
  tags: ma_devel_rnotes
  block:

    - name: "Devel: Create directories for release notes"
      tags: ma_rnotes_path
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group | d(omit) }}"
        mode: "{{ ma_devel_dmode | d(omit) }}"
      loop:
        - "{{ ma_rnotes_core_dir }}"
        - "{{ ma_rnotes_build_dir }}"

    - name: "Devel: Get core release notes {{ ma_rnotes_core_list }}"
      check_mode: false # Note 1.
      vars:
        _file: CHANGELOG-v{{ item }}.rst
        _url: "{{ (ma_rnotes_core_url ~ item, 'changelogs', _file) | community.general.path_join }}"
      environment:
        CRYPTOGRAPHY_OPENSSL_NO_LEGACY: '1'
      ansible.builtin.get_url:
        url: "{{ _url }}"
        dest: "{{ (ma_rnotes_core_dir, _file) | community.general.path_join }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group }}"
        mode: "0644"
      loop: "{{ ma_rnotes_core_list }}"
      loop_control:
        label: "{{ _url }}"

    - name: "Devel: Get build release notes {{ ma_rnotes_build_list }}"
      check_mode: false #  Note 1.
      vars:
        _file: CHANGELOG-v{{ item }}.rst
        _url: "{{ (ma_rnotes_build_url, item, _file) | community.general.path_join }}"
      environment:
        CRYPTOGRAPHY_OPENSSL_NO_LEGACY: '1'
      ansible.builtin.get_url:
        url: "{{ _url }}"
        dest: "{{ (ma_rnotes_build_dir, _file) | community.general.path_join }}"
        owner: "{{ ma_devel_owner }}"
        group: "{{ ma_devel_group }}"
        mode: "0644"
      loop: "{{ ma_rnotes_build_list }}"
      loop_control:
        label: "{{ _url }}"

# Notes:
#
# 1) The module get_url does not support diff_mode. It will always
#    report *changed* in check_mode.

# EOF
