---
# tasks for ansible

- name: Add {{ ansible_os_family }} specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [bsd_packages, linux_packages, ma_vars]

- name: Debug
  vars:
    msg: |
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      ma_install [ {{ ma_install }} ]
      ma_packages [ {{ ma_packages }} ]
      ma_config_type [ {{ ma_config_type }} ]
      ma_config_template_default [ {{ ma_config_template_default }} ]
      ma_config [ {{ ma_config|to_nice_yaml }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: ma_debug
  tags: ma_debug

- import_tasks: packages.yml
  when: ma_install
  tags: [bsd_packages, linux_packages, ma_packages]

- import_tasks: configure.yml
  when: ma_config > 0
  tags: ma_config

# EOF
...
