---

- name: Install Ansible packages FreeBSD
  pkgng:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ ma_packages }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: Install Ansible ports FreeBSD
  portinstall:
    name: "{{ item }}"
    state: "present"
    use_packages: "{{ freebsd_use_packages }}"
  with_items: "{{ ma_packages }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

- name: Install Ansible packages Linux
  package:
    name: "{{ item }}"
  with_items: "{{ ma_packages }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")

# EOF
...
