---

- name: "packages: Install Ansible packages FreeBSD"
  pkgng:
    name: "{{ ma_packages }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: "packages: Install Ansible ports FreeBSD"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ ma_packages }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

- name: "packages: Install Ansible packages Linux"
  package:
    name: "{{ item }}"
  loop: "{{ ma_packages }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")

# EOF
...
