---

- name: "plugins: Create directories"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ ma_plugins_path }}"
    - "{{ ma_src_path }}"
  tags: ma_plugins_dirs

- name: "plugins: Download archives"
  ansible.builtin.get_url:
    url: "{{ item.archive_url }}"
    dest: "{{ ma_src_path }}/{{ item.archive }}"  # Note 1
    checksum: "{{ item.checksum }}"
  loop: "{{ ma_plugins }}"
  loop_control:
    label: "{{ item.archive }}"
  tags: ma_plugins_download

- name: "plugins: Extract archives"
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ ma_src_path }}/{{ item.archive }}"
    dest: "{{ ma_plugins_path }}"
    creates: "{{ item.creates|default(omit) }}"
  loop: "{{ ma_plugins }}"
  loop_control:
    label: "{{ item.archive }}"
  when: not ansible_check_mode
  tags: ma_plugins_extract

- name: "plugins: Create links"
  ansible.builtin.file:
    state: link
    src: "{{ ma_plugins_path }}/{{ item.dest }}"
    dest: "{{ ma_plugins_path }}/{{ item.link }}"
  loop: "{{ ma_plugins }}"
  loop_control:
    label: "{{ item.dest }}"
  when:
    - item.link is defined
    - item.dest is defined
    - not ansible_check_mode
  tags: ma_plugins_link

- name: "plugins: Create lists"
  block:
    - name: "plugins: Create list of used ini_keys ma_plugins_inikeys"
      ansible.builtin.set_fact:
        ma_plugins_inikeys: "{{ ma_plugins|json_query('[].plugins[].ini_key')|list|unique }}"
    - name: "plugins: Debug ma_plugins_inikeys"
      ansible.builtin.debug:
        var: ma_plugins_inikeys
      when: ma_debug|bool
    - name: "plugins: Create list of plugins ma_plugins_list"
      ansible.builtin.set_fact:
        ma_plugins_list: "{{ ma_plugins|json_query('[].plugins[].{path: path,
                                                                  ini_key: ini_key,
                                                                  enable: enable}')
                                                                  |list }}"
    - name: "plugins: Debug ma_plugins_list"
      ansible.builtin.debug:
        var: ma_plugins_list
      when: ma_debug|bool
    - name: "plugins: Group plugins by ini_key to ma_plugins_grouped"
      ansible.builtin.set_fact:
        ma_plugins_grouped: "{{ ma_plugins_list|groupby('ini_key') }}"
    - name: "plugins: Debug ma_plugins_grouped"
      ansible.builtin.debug:
        var: ma_plugins_grouped
      when: ma_debug|bool
    - name: "plugins: Create list of ini_key ma_plugins_inikeys_list"
      ansible.builtin.set_fact:
        ma_plugins_inikeys_list: "{{ ma_plugins_sections.keys() }}"
    - name: "plugins: Debug ma_plugins_inikeys_list"
      ansible.builtin.debug:
        var: ma_plugins_inikeys_list
      when: ma_debug|bool
    - name: "plugins: Create lists of paths ma_plugins_paths_list"
      ansible.builtin.set_fact:
        ma_plugins_paths_list: "{{ ma_plugins_paths_list +
                                   [ {item.0: {'paths': item.1|json_query('[?enable].path')} } ] }}"
      loop: "{{ ma_plugins_grouped }}"
      loop_control:
        label: "{{ item.0 }}"
    - name: "plugins: Debug ma_plugins_paths_list"
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ ma_plugins_paths_list }}"
      loop_control:
        label: "{{ item.keys()|list|first }}"
      when: ma_debug|bool
  tags: ma_plugins_lists

- name: "plugins: Test used ini_keys"
  ansible.builtin.fail:
    msg: "[ERROR] wrong ini_key: {{ item }}. End of play."
  loop: "{{ ma_plugins_inikeys }}"
  when: item not in ma_plugins_inikeys_list
  tags: ma_plugins_test_inikeys

# Notes
#
# Note 1: If dest is a dictionary get_url will always download the file
# Fix docs get_url dest comment. Checksum does not prevent download. #73185
# https://github.com/ansible/ansible/pull/73185

# EOF
...
