---
- name: Declare ma_owner when undefined
  when: ma_owner is undefined
  block:

    - name: "Vars: Get the user"
      become: false
      ansible.builtin.setup:
        gather_subset: user

    - name: "Vars: Debug user ma_debug={{ ma_debug }}"
      when: ma_debug | bool
      ansible.builtin.debug:
        msg: |
          ansible_user: {{ ansible_user | d('UDEFINED') }}
          ansible_user_id: {{ ansible_user_id | d('UDEFINED') }}

    - name: "Vars: Declare ma_owner"
      ansible.builtin.set_fact:
        ma_owner: "{{ ansible_user | d(ansible_user_id) }}"

- name: "Vars: Include OS vars"
  vars:
    al_os_vars_path: "{{ ansible_parent_role_paths.0 }}"
  ansible.builtin.include_role: # noqa: var-naming[no-role-prefix]
    name: vbotka.ansible_lib
    tasks_from: al_include_os_vars_path

- name: "Vars: Override ma_packages"
  when: ma_packages_override is defined
  ansible.builtin.set_fact:
    ma_packages: "{{ ma_packages_override }}"

- name: "Vars: Override ma_pip_executable"
  when: ma_pip_executable_override is defined
  ansible.builtin.set_fact:
    ma_pip_executable: "{{ ma_pip_executable_override }}"

- name: "Vars: Override ma_pip_requirements"
  when: ma_pip_requirements_override is defined
  ansible.builtin.set_fact:
    ma_pip_requirements: "{{ ma_pip_requirements_override }}"

# EOF
