---

- name: "Vars: Include OS vars"
  ansible.builtin.include_role:
    name: vbotka.ansible_lib
    tasks_from: al_include_os_vars_path
  vars:
    al_os_vars_path: "{{ ansible_parent_role_paths.0 }}"  # noqa: var-naming[no-role-prefix]

# EOF
...
