---
# All rights reserved (c) 2020-2024, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Ansible playbook: preamble.yml
#
# Description:
#
#   This playbook configures parameters of listed playbooks. Fit the
#   parameters to your needs.
#
# Example:
#
#   shell> ansible-playbook preamble.yml
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# https://github.com/vbotka/ansible-ansible/tree/master/contrib/playbooks

- name: Configure playbooks
  hosts: localhost

  tasks:

    - name: Update parameters of the playbooks.
      ansible.builtin.blockinfile:
        path: "{{ item }}"
        insertafter: ^- hosts(.*)$
        marker: "# {mark} ANSIBLE MANAGED BLOCK preamble"
        block: |2
            connection: ssh
            remote_user: admin
            become: true
            become_user: root
            become_method: sudo
      # validate: ansible-playbook %s --syntax-check
      loop:
        - freebsd-custom-img.yml

# EOF
...
