---

- name: "Roles-objects: Include vars {{ item ~ '/meta/main.yml' }}"
  ansible.builtin.include_vars:
    file: "{{ item }}/meta/main.yml"
    name: my_meta

- name: "Roles-objects: Get role Galaxy info"
  ansible.builtin.set_fact:
    rm_roles_meta: "{{ rm_roles_meta | d({}) | combine({item: my_meta}) }}"

- name: "Roles-objects: Include vars {{ item ~ '/.travis.yml' }}"
  ansible.builtin.include_vars:
    file: "{{ item }}/.travis.yml"
    name: my_travis

- name: "Roles-objects: Get role Travis info"
  ansible.builtin.set_fact:
    rm_roles_travis: "{{ rm_roles_travis | d({}) | combine({item: my_travis}) }}"

# EOF
