---
# All rights reserved (c) 2019-2024, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Create links
#
# Parameters:
#   my_links_file ............. file with the list of the links
#   my_base_path .............. base directory
#
# Notes:
#   * Used by ansible-workbench.sh
#   * vars are defaults. Will be overriden by --extra-vars
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# https://github.com/vbotka/ansible-ansible/contrib/workbench

- name: Create links
  hosts: localhost
  connection: local
  debugger: on_failed
  gather_facts: false

  vars:

    # my_version: "1.0.1-CURRENT"
    my_version: 1.0.0
    my_base_path: "{{ lookup('env','HOME') }}/.ansible"
    my_links_file: vars/links.yml

  tasks:
    - name: Include list of links from {{ my_links_file }}
      ansible.builtin.include_vars: "{{ my_links_file }}"
    - name: Debug variables
      when: debug | d(false) | bool
      vars:
        msg: |
          my_version: {{ my_version }}
          my_base_path: {{ my_base_path }}
          my_links_file: {{ my_links_file }}
          ansible_check_mode: {{ ansible_check_mode }}
          requirements:
            {{ requirements | to_nice_yaml(indent=2) | indent(2) }}
      ansible.builtin.debug:
        msg: "{{ '{}'.format(msg) }}"

    - name: Debug links
      when: debug | d(false) | bool
      ansible.builtin.debug:
        msg: path {{ item.path }} link {{ item.link }}
      loop: "{{ requirements }}"

    - name: Create links to absolute paths
      when: item.path.0 == '/'
      ansible.builtin.file:
        state: link
        src: "{{ item.path }}"
        dest: "{{ my_base_path }}/{{ item.link }}"
      loop: "{{ requirements }}"

    - name: Create links to relative paths
      when: item.path.0 != '/'
      ansible.builtin.file:
        state: link
        src: "{{ my_base_path }}/{{ item.path }}"
        dest: "{{ my_base_path }}/{{ item.link }}"
      loop: "{{ requirements }}"

# EOF
